version: '3.8'
services:
  ecommerce-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-api 
    restart: always
    ports:
      - 8070:8070
    depends_on:
      - postgres
    env_file:
      - .env.docker

  postgres:
    image: postgres:13
    container_name: postgresprisma
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.docker
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: ecommerce-prisma-docker-db
